name: Build-and-Push

# Run this workflow on every push to any branch
on: [push]

# Global env-vars (available to every job/step)
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cloud-latency-monitor   # ⚠️ all lower-case

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    # 1) Check out repository code
    - uses: actions/checkout@v4

    # 2) Log in to GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 3) Build the image from app/Dockerfile and push it
    - name: Build & Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./app            # folder that holds the Dockerfile
        file: ./app/Dockerfile    # explicit Dockerfile path
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}