name: Build-and-Push

on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      # pull your code
      - uses: actions/checkout@v4

      # login to GitHub Container Registry (free, built-in)
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build the image found in app/Dockerfile and push it
      - uses: docker/build-push-action@v5
        with:
          context: ./app          # ← folder where Dockerfile lives
          file: ./app/Dockerfile  # ← explicit path
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
